services:
  core_regulus_backend:
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - shared_net
    environment:
      - ENVIRONMENT=production
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - JWT_PRIVATE_KEY
      - JWT_PUBLIC_KEY
networks:
  shared_net:
    external: true