create user <new-user> with encrypted password '**********';
grant CONNECT on database coreregulus to <new-user>;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO <new-user>;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO <new-user>;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO <new-user>;

GRANT usage ON SCHEMA users TO <new-user>;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA users TO <new-user>;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA users TO <new-user>;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA users TO <new-user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA users
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO <new-user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA users
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO <new-user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA users
GRANT EXECUTE ON FUNCTIONS TO <new-user>;

GRANT usage ON SCHEMA service TO <new-user>;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA service TO <new-user>;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA service TO <new-user>;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA service TO <new-user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA service
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO <new-user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA service
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO <new-user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA service
GRANT EXECUTE ON FUNCTIONS TO <new-user>;

GRANT usage ON SCHEMA config TO <new-user>;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA config TO <new-user>;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA config TO <new-user>;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA config TO <new-user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA config
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO <new-user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA config
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO <new-user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA config
GRANT EXECUTE ON FUNCTIONS TO <new-user>;

GRANT usage ON SCHEMA shared TO <new-user>;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA shared TO <new-user>;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA shared TO <new-user>;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA shared TO <new-user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA shared
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO <new-user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA shared
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO <new-user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA shared
GRANT EXECUTE ON FUNCTIONS TO <new-user>;

