create user <new-user> with encrypted password '**********';
grant CONNECT on database coreregulus to <new-user>;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO <new-user>;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO <new-user>;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO <new-user>;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA users TO <new-user>;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA users TO <new-user>;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA users TO <new-user>;

ALTER DEFAULT PRIVILEGES IN SCHEMA users
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO <new-user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA users
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO <new-user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA users
GRANT EXECUTE ON FUNCTIONS TO <new-user>;