name: Core Regulus Backend Deploy
run-name: ${{ github.actor }} is deploying the project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Personal Projects

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{secrets.SSH}}
          source: "*"
          target: "/home/ci/core-regulus/backend"